export const ActionTypes = {
    SELLER_SIGN_UP_SUCCESS: "SELLER_SIGN_UP_SUCCESS",
    SELLER_SIGN_IN_SUCCESS: "SELLER_SIGN_IN_SUCCESS",
    ADMIN_SIGN_IN_SUCCESS:"ADMIN_SIGN_IN_SUCCESS",
    
    GET_CURRENT_SELLER_PRODUCTS: "GET_CURRENT_SELLER_PRODUCTS",

    GET_STORES: "GET_STORES",

    NAVIGATION_PROPS: "NAVIGATION_PROPS",

    GET_DATA_FROM_ASYNCSTORAGE: "GET_DATA_FROM_ASYNCSTORAGE",
}